### ISSUE TITLE
Remove reference to firebase in preinstall/postinstall

### ISSUE THREAD

**Issue by jlooper** [NativeScript/template-master-detail-kinvey-ng#2]
In the preinstall and postinstall scripts, there are references to firebase which throw errors:

```
postinstall script running...
Updating package.json scripts for linting...
Update google services configuration for firebase...
{ Error: ENOENT: no such file or directory, open '/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/App_Resources/Android/google-services.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at replaceAppId (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:63:22)
    at updateFirebaseConfigAppId (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:52:9)
    at Object.<anonymous> (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:14:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/App_Resources/Android/google-services.json' }
{ Error: ENOENT: no such file or directory, open '/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/App_Resources/iOS/GoogleService-Info.plist'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at replaceAppId (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:63:22)
    at updateFirebaseConfigAppId (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:53:9)
    at Object.<anonymous> (/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/tools/postinstall.js:14:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/Looper/Desktop/myKinveyApp/node_modules/nativescript-ng-ui-kit-master-detail-kinvey/App_Resources/iOS/GoogleService-Info.plist' }
```

These can be removed, I think.

**Comment by manoldonev** [comment]
Hey @jlooper, this will be fixed with https://github.com/NativeScript/template-master-detail-kinvey-ng/pull/3.

This template is still WIP (it is not in sync with the latest version of https://github.com/NativeScript/template-master-detail-ng UX-wise, neither is it published to npm, nor its versioning is up-to-date with the pattern of the rest of the templates).
